In [1]:
import pandas as pd

In [12]:
import pandas as pd

df = pd.read_parquet(
    "/Users/haaminh109/Desktop/Minh/Tài liệu học tập (DSEB)/Kì 7/Big Data/lakehouse-opt/data/raw/yellow_tripdata_2025-01.parquet",
)

df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [13]:
df[df["fare_amount"] == df["fare_amount"].max()]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
1780915,1,2025-01-20 12:07:18,2025-01-20 12:12:42,1.0,1.6,1.0,N,138,8,4,863372.12,6.75,0.5,0.0,0.0,1.0,863380.37,0.0,1.75,0.0

In [10]:
df[df["trip_distance"] == 0]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,trip_id
3,1,2025-01-01 00:27:40,2025-01-01 00:59:30,1,0.0,1,N,168.0,76.0,1,50.50,0.0,0.5,0.00,6.94,1,58.94,0.0,0.0,trip_202501_000497
87,1,2025-01-01 00:49:48,2025-01-01 00:49:48,1,0.0,1,Y,87.0,264.0,2,20.06,0.0,0.0,0.00,0.00,0,20.06,0.0,0.0,trip_202501_000091
430,1,2025-01-01 00:42:42,2025-01-01 00:42:44,0,0.0,1,N,261.0,261.0,1,3.00,3.5,0.5,2.35,0.00,1,10.35,2.5,0.0,trip_202501_000696
551,2,2025-01-01 00:56:49,2025-01-01 00:56:54,4,0.0,5,N,164.0,164.0,1,20.00,0.0,0.0,7.05,0.00,1,30.55,2.5,0.0,trip_202501_000611
593,2,2025-01-01 00:57:08,2025-01-01 00:57:16,3,0.0,5,N,141.0,141.0,1,30.00,0.0,0.0,0.00,0.00,1,33.50,2.5,0.0,trip_202501_000353
624,2,2025-01-01 00:37:43,2025-01-01 00:37:53,1,0.0,5,N,148.0,148.0,1,12.00,0.0,0.0,2.00,0.00,1,17.50,2.5,0.0,trip_202501_000200